### ISSUE TITLE
Can we get an interface to change the sharer url prefix for each social network?

### ISSUE THREAD

**Issue by xiaoyaohust** [koddr/vue-goodshare#5]
For example, the prefix for pinterest is hardcoded as

https://pinterest.com/pin/create/button/

However, this url will complain that there is no image for the pin if I don't pass a media value.

There is another URL which is https://www.pinterest.com/pin/find/?url=@url
It can load all the images in the page and let customer to choose one image and then create the pin.
This fits our use case and it exactly what we want.

But if I use this module, I find there is no way that I can change the hardcoded url to the "find" url above.

**Comment by koddr** [comment]
Hello, @xiaoyaohust 

I don't use Pinterest so long. Can you understand, what's difference between this links (in your issue)? Maybe I switch to second link in master branch of `vue-goodshare` if first link don't use for any more.

Wait for your answer. Btw, thanks for support!

**Comment by xiaoyaohust** [comment]
The first link is to create a pin directly but it needs the client to provide a media image. Since pInterest is image based, it will fail to create a pin if there is no image provided.

The second link is that pInterest will load all the images in your shared page and let the customer to choose one. After the choosing, it will create a pin.

**Comment by florentpeyrard** [comment]
Hi,

I'd advice to keep https://pinterest.com/pin/create/button/ because this is the recommended endpoint, as stated by Pinterest : "The Save button is the best way for your business to get content on Pinterest. With just one click, visitors can save content they like on your site to Pinterest, which helps even more Pinners discover you.".

I would also recommend to replace canonicalUrl= by url=, which allows the pin to point to the source website, otherwise it only points to the source image, which is useless in terms of attracting-Pinterest-users-to-the-original-website.

Reference : https://developers.pinterest.com/docs/widgets/save/

By the way, thanks a lot for this beautiful library :)

**Comment by florentpeyrard** [comment]
Just one more detail : in my case, if the source page has no image, I feed media= with the website logo, as a fallback image.
